version: '3.8'

services:
  backend:
    container_name: mall_backend
    build:
      context: ./
      dockerfile: Dockerfile
    command: gunicorn --bind 0.0.0.0:8000 app:app
    expose:
      - "8000"
    ports:
      - "8000:8000"
    env_file:
      - ./.env           # MYSQL_HOST, MYSQL_USER 등
    restart: always
    depends_on:
      - db
    networks:         # ← network → networks 로 수정
      - mall_network

  db:
    container_name: mall_db
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 0000
      MYSQL_DATABASE: mall
      MYSQL_USER: appuser1
      MYSQL_PASSWORD: 0000
    volumes:
      - mall_db_data:/var/lib/mysql
    networks:
      - mallnet

volumes:
  mall_db_data:

networks:
  mall_network:
    external: true
  mallnet:
    driver: bridge

